version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  authentication:
    build:
      context: .
      dockerfile: Dockerfile.authentication
    environment:
      - AUTH_MONGO_URI=mongodb://mongo:27017/ounass-auth
      - AUTH_PORT=3001
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    ports:
      - 3001:3001
    networks:
      - ounass-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - GATEWAY_PORT=3000
      - AUTH_PORT=3001
      - JWT_SECRET=supersecret
    depends_on:
      - authentication
    ports:
      - 3000:3000
    networks:
      - ounass-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongo_data:

networks:
  ounass-net:
    driver: bridge
