version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  authentication:
    build:
      context: .
      dockerfile: Dockerfile.authentication
    environment:
      - AUTH_MONGO_URI=mongodb://mongo:27017/ounass-auth
      - AUTH_PORT=3001
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    ports:
      - 3001:3001
    networks:
      - ounass-net

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - GATEWAY_PORT=3000
      - AUTH_PORT=3001
      - JWT_SECRET=supersecret
    depends_on:
      - authentication
    ports:
      - 3000:3000
    networks:
      - ounass-net

volumes:
  mongo_data:

networks:
  ounass-net:
    driver: bridge
